name: Sync GraphQL schemas

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Get sources
        uses: actions/checkout@v2

      - uses: kamilkisiela/graphql-inspector@master
        with:
          name: Inspect Grabase schema
          schema: api.grafbase.com/schema.graphql
          endpoint: https://api.grafbase.com/graphql

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Sync schemas
        run: yarn sync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push any changes
        run: |
          git config --global user.name "${GIT_USER}"
          git config --global user.email "${GIT_USER}@users.noreply.github.com"
          if git commit -a -m "Sync schema changes"; then
              git push origin main
          fi
        env:
          GIT_USER: graphql-schemas-bot
