name: Sync GraphQL schemas

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Get sources
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Sync schemas
        run: |
          git config --global user.name "${GIT_USER}"
          git config --global user.email "${GIT_USER}@users.noreply.github.com"
          bun run sync
          git push origin main
        env:
          GIT_USER: graphql-schemas-bot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
